### ISSUE TITLE
Document id for newly created document?

### ISSUE THREAD

**Issue by jaylyerly** [tb1337/paperless-api#47]
Thanks for making this library available.  I've been working with it today and have everything almost working for my project!

I'm writing an import script to create some new documents in paperless-ngx with tags and notes.  I've worked out the tag situation -- I create tags as needed, get the associated ids (matching on the name) and create the new document with the necessary tag ids.  

The problem I'm running into is adding the note.  From what I gather, I need to do a `paperless.documents.notes.create` with the note string and the document id.  That make sense, but I'm not sure how to get the document's id when creating a new document.  What's the best way to go about that?

**Comment by tb1337** [comment]
That's in fact something I'm currently not happy with: you have to retrieve a specific document object at first. pypaperless wraps around requesting URLs, so imagine each get(), one(), iterate(), create(), update() and delete() method as a single (or more on paginated results) http request(s). 

That's was on my list, I wanted to make the documents sub endpoints (notes, files) feel less odd for people working with pypaperless. Some days ago I was examining how to actually achieve that. One possible solution was moving that sub endpoint code into the Document model class, but I wasn't happy with that either: a model is a model and nothing else. 😁

Well, I skipped working on it because I asked myself how often I would actually create and delete document notes. There is currently no single use-case beside from somehow logging stuff directly to a document, I can imagine. If you don't care about wasting primary keys of document notes, you could use them as metadata stores for serialized data, as you have to delete/create notes when updating that data again.

The workflow could be:

```python
#...
from pypaperless.models.shared import TaskStatus

# its Paperless-ngx REST API design to return a task_id here, so we do that too
task_id = await paperless.documents.create( new_document )

# wait for Paperless-ngx to have successfully consumed the document
task = await paperless.tasks.one( task_id )
if task.status == TaskStatus.SUCCESS:
    document_id = task.related_document

    await paperless.documents.notes.create( document_id, "My new document note.")
```

When fetching the task immediately after creating a document, the task status could be still PENDING. You must check periodically if it's SUCCESS (we are in asyncio mode, you could write a task for it). Another solution could be moving your code into a POST_CONSUMPTION_SCRIPT executed by Paperless-ngx after finishing consuming, where the document id of your newly created document is already available.

https://docs.paperless-ngx.com/advanced_usage/#post-consume-script

Hope that helps :)

**Comment by jaylyerly** [comment]
Thanks!  This is super helpful.  I suspected that I'd need to do something like this with polling the task until the document has been ingested.  With these clues, I think I've got my script doing pretty much everything I need.

For a little more context, I'm writing a script to take Evernote exports (ENEX files) and move the PDFs into Paperless-ngx.  I've mostly used Evernote as a PDF organizer, so Paperless is a good replacement for me.  Some of the notes in Evernote have some text along with the attached PDF.  With your pointers, I'm able to attach that text in the `notes` field in Paperless.  This is a one-time import situation, so I'm not worried about updating the notes in the future.  I'm also able to preserve tags and creation dates, so it's working out pretty well for me.

Thanks again for the quick reply and the handy library.  Good work!
