### ISSUE TITLE
Error while using https

### ISSUE THREAD

**Issue by tzepter** [tb1337/paperless-api#49]
When I try something like that:

```
paperless = Paperless(
    "https://servername/paperless/api/",
    "xxxxx",
    request_opts={"ssl": True}
)
```
I get the error
```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host https:80 ssl:True [Name or service not known]
ERROR    asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f58441fc210>
```
I wonder 
(a) why port 80 is used and
(b) how I can use a SSLContext or directly cacert.pem.

**Comment by tb1337** [comment]
Hi, thanks for your issue.

Please initialize the Paperless object by just passing the `servername/paperless` part of your URL, pypaperless will create the full api path on its own: `http://{self.host}/api/{path}"`. And yes, there is a relic from the beginning of the project, which I will fix tomorrow.

Is your Paperless-ngx behind a reverse proxy which enforces https and a sub-path? Please tell me what happens if you request the following urls in your browser.
1. https://servername/paperless/api/
2. http://servername/paperless/api/

It should respond with 200 OK on both requests and that json object:
![image](https://github.com/tb1337/paperless-api/assets/38990875/e13410a1-7216-46e9-bcc4-497291ad31c0)

You may pass any option via request_opts, which an aiohttp.ClientSession allows for its request method: `self._session.request(method, url, **kwargs)`. I will update the documentation to be more clear about it.

**Comment by hapm** [comment]
Ran into this as well. I would like to use the `https` endpoint as `http` is firewalled on my paperless instance.

**Comment by tzepter** [comment]
Hi, yes, my paperless-ngx is behind a reverse proxy which enforces https and a sub-path.

I have to use the https protocol prefix in the host variable, because otherwise the API url would be used with the http protocol as you pointed out. Your both requests

    https://servername/paperless/api/
    http://servername/paperless/api/

lead to the same error message I mentioned above. Furthermore, if I use

    https://servername:443/paperless/api/

the result is the same ("cannot connect to host https:80").

**Comment by hapm** [comment]
For me there was some paperless configuration missing to get the correct api urls back:
```
PAPERLESS_USE_X_FORWARD_HOST=1
PAPERLESS_USE_X_FORWARD_PORT=1
PAPERLESS_PROXY_SSL_HEADER=["HTTP_X_FORWARDED_PROTO", "https"]
```

This was because of a reverse proxy terminating the ssl connection and django ignoring the specific headers for that. But getting the api urls from the api root path still didn't work because of the hardcoded protocol [here](https://github.com/tb1337/paperless-api/blob/6e019987bb7eb0e585bf3730f8cdade4ae0387aa/pypaperless/__init__.py#L197). Patching that to https worked for me as a workaround, but it would be better if that could be configured.

The patched version allows me to use `Paperless("hostname:443", ..., request_opts={ "ssl": False })` where `request_opts={ "ssl": False }` disables the cert check but still allows for ssl if there is https in the url.

**Comment by tb1337** [comment]
I'm using the same paperless reverse proxy configuration as @hapm does, my development paperless container is simply http.

Whatever, I gonna make use of yarl to parse all necessary url parts, as it's already a sub dependency. Goal is letting developers pass either a single hostname, or a complete url path to the Paperless object (especially when using sub paths as @tzepter mentioned above). It will parse everything it needs itself from the given infos. When just passing a hostname, the Paperless object initiates a basic discovery task for checking if https is available, https>http. I don't want to over engineer things here, because it's just a rest wrapper and users of it are clever enough to handle urls right.

**Comment by tzepter** [comment]
Hm, I understood you - @tb1337 - to mean that if I extend the paperless environment with the variables shown by @hapm, pypaperless should work if I use a complete URL path. This is not the case: I still get the error message 

`Cannot connect to host https:80 ssl:False [Name or service not known]`

At the same time, however, this works without any problem:

```
import httpx
host = "https://server/paperless"
token = "xxxx"
resp = httpx.post(host + "/api/documents/post_document/",
                      headers={"Authorisation": "Token " + token},
                      files={'document': ('test.pdf', open('./test.pdf', 'rb'), 'application/pdf')},
                      data={"title": "My first upload", "created": "2023-12-21"},
                      verify='./cacert.pem')
    if resp.status_code == 200:
          pass
```

Why does `aiohttp` think to use port 80?

**Comment by tb1337** [comment]
It does that because I implemented a bug, as mentioned above. Currently fixing it. ;)

**Comment by tb1337** [comment]
In order to request via http, one has to explicitly instantiate the Paperless object this way: ```paperless = Paperless("http://hostname")```.

You have to instantiate it so: ```paperless = Paperless("https://hostname/paperless")```, ```Paperless("hostname/paperless")``` will work too (defaults to https).

I'll push the branch soon, could you test with the branch if the solution is working for you now? I tested it locally against my dev server (http) and prod server (https), it is working for me. Before I can release a new version, I have to write docs and solve another issue. I'm busy this weekend, so we have to wait until Monday for that.

**Comment by tzepter** [comment]
it seem to work. I am saying this so carefully because there was a error, but it is very likely due to another reason. To verify that I used the file under example/usage.py and fit it to my environment:

```
import asyncio
import logging
import os.path
import sys
import ssl
from pypaperless import Paperless

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))

logging.basicConfig(
    level=logging.DEBUG,
    format="%(levelname)-8s %(name)s - %(message)s",
)

from pypaperless import Paperless  # noqa

context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.load_verify_locations('./cacert.pem')
context.verify_mode = ssl.CERT_REQUIRED
context.check_hostname = True

paperless = Paperless(
    "https://server/paperless/",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    request_opts={"ssl_context": context}
)

async def main():
    """Execute main function."""
    async with paperless as p:
        correspondents = {}
        async for item in p.correspondents.iterate():
            correspondents[item.id] = item

        documents = await p.documents.get(page=1)
        for item in documents.items:
            print(
                f"Correspondent of document {item.id} is: {correspondents[item.correspondent].name}!"  # noqa
            )
            await asyncio.sleep(0.25)


if __name__ == "__main__":
    asyncio.run(main())
```
The result is:

```
DEBUG    asyncio - Using selector: EpollSelector
INFO     pypaperless[servername] - Fetching api endpoints.
DEBUG    pypaperless[servername] - Json-Request GET (200): https://servername/paperless/api/
DEBUG    pypaperless[servername] - Unused endpoints: logs
INFO     pypaperless[servername] - Initialized.
DEBUG    pypaperless[servername] - Json-Request GET (200): https://servername/paperless/api/correspondents/?page=1&page_size=50
DEBUG    pypaperless[servername] - Json-Request GET (200): https://histton/servername/api/documents/?page=1&page_size=100
Correspondent of document 18 is: XXX!
Correspondent of document 15 is: XXX!
Correspondent of document 21 is: XXXXXXXXXXX!
INFO     pypaperless[servername] - Closed.
Traceback (most recent call last):
  File "/home/user/Dokumente/code/python/EloMigration/example.py", line 50, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/Dokumente/code/python/EloMigration/example.py", line 36, in main
    async with paperless as p:
  File "/home/user/Dokumente/code/python/EloMigration/env/lib/python3.11/site-packages/pypaperless/__init__.py", line 276, in __aexit__
    raise exc
  File "/home/user/Dokumente/code/python/EloMigration/example.py", line 44, in main
    f"Correspondent of document {item.id} is: {correspondents[item.correspondent].name}!"  # noqa
                                               ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: None
```
If I used `request_opts={"ssl": False}` the result is the same.

**Comment by tb1337** [comment]
Yes. It seems like one of your documents doesn’t have a correspondent. None raises the KeyError and there we are. Am I right?

**Comment by tzepter** [comment]
You are right. I just exercise document migration now. ;)
Thx!

**Comment by tb1337** [comment]
Thanks for your issue guys. I will merge until Monday
